name: Zed Compilation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - master
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  zed:
    runs-on: windows-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v4

      - name: Setting up 
        run: |
          git config --system core.longpaths true

      - name: Doing some weird Windows stuff 
        shell: pwsh
        run: | 
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
        

      - name: Cloning Zed
        run: git clone https://github.com/zed-industries/zed.git

      - name: Compiling Zed
        run: |
          cd zed
          cargo build --release
          
      - name: Uploading a successful Release build artifact.
        uses: actions/upload-artifact@v4.3.3
        with:
          name: zed_build
          path: ./zed/target/release/zed.exe
