name: Zed Compilation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  zed:
    runs-on: windows-latest

    steps:
      - name: Setting up
        uses: actions/checkout@v4

      - name: Cloning Zed
        run: git clone https://github.com/zed-industries/zed.git

      - name: Compiling Zed
        run: |
          cd zed
          cargo build --release
          
      - name: Uploading a successful Release build artifact.
        uses: actions/upload-artifact@v4.3.3
        with:
          name: zed_build
          path: ./zed/target/release/zed.exe
